### ISSUE TITLE
[Feature Request] Read mybama username and password from environment variables

### ISSUE THREAD

**Issue by jmbeach** [mwleeds/MyBamaChecker#2]
I think it might be more secure to have your username and password stored in the environment than to type them in to the console or store them in possibly multiple files.

**Comment by mwleeds** [comment]
A configuration file is slightly more user-friendly and secure right? Because you usually have to set environment variables on the command line which means they're stored in your shell history. Hopefully 215afaa4c12fadb4f50ac61c293c6211e4dfc226 works as intended.

**Comment by jmbeach** [comment]
Yeah, now that I think about it, a config is a little less cumbersome. The only thing I don't like about configs is the possibility of accidentally tracking them with git
