### ISSUE TITLE
[Feature Request] Trigger

### ISSUE THREAD

**Issue by jmbeach** [mwleeds/MyBamaChecker#4]
It would be cool if in CheckGrades.py there was a way to run a command as an optional third argument if the grades did change. That way you could have it run over and over on some sort of job and get notified by e-mail or something whenever all your grades are up.

**Comment by mwleeds** [comment]
I accomplished that by putting this Bash command in my crontab:

```
*/15 * * * * python3 /root/MyBamaChecker/CheckGrades.py 2>>/root/CheckGrades.log | grep "grade has been posted" && echo "" | mail -s "grade posted" mwl458@gmail.com
```

(if the grep fails the mail command isn't executed)
but you're right it could be integrated into the script. I'm not sure there's an OS-independent way to do it but I think it would be pretty easy to do if you assume the "mail" command is setup.

**Comment by jmbeach** [comment]
Didn't know you could short-circuit with grep. Pretty cool. 

I think to include Windows users, there is some function in the OS library that can run any command as a string, but what you wrote satisfies my needs
